version: '3.4'

services:
  hotpot.api:
    image: ${DOCKER_REGISTRY-}hotpotapi
    build:
      context: .
      dockerfile: Hotpot.Api/Dockerfile
    depends_on:
        - db
  db:
      image: "mcr.microsoft.com/mssql/server"
      environment:
          SA_PASSWORD: "Your_password123"
          ACCEPT_EULA: "Y"
      ports:
        - "1433:1433"
